"""Public schema and integrity identifiers."""

CASE_SCHEMA = "pvs-case/2"
LEGACY_CASE_SCHEMA = "pvs-case/1"
EVIDENCE_SCHEMA = "pvs-evidence/3"
V2_EVIDENCE_SCHEMA = "pvs-evidence/2"
LEGACY_EVIDENCE_SCHEMA = "pvs-evidence/1"
MANIFEST_SCHEMA = "pvs-manifest/3"
V2_MANIFEST_SCHEMA = "pvs-manifest/2"
LEGACY_MANIFEST_SCHEMA = "pvs-manifest/1"
NETCDF_DECODING_PROFILE = "pvs-netcdf/1"
CANONICALIZATION = "RFC8785"
HASH_ALGORITHM = "sha256"
EVIDENCE_PREFIX = "pvs:sha256:"
HTML_REPORT_PROFILE = "pvs-html/3"
PDF_REPORT_PROFILE = "pvs-pdf/3"
FINDING_PROJECTION = "pvs-finding-projection/1"
FINDING_PREFIX = "pvs-finding:v1:sha256:"
COMPARISON_PROFILE = "pvs-comparison/2"
